parameters:
  name: 'Linux'

jobs:
- job: '${{ parameters.name }}'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      GIT_DESCRIBE=$(git describe --tags --dirty --always)
      echo "##vso[task.setvariable variable=BUILD_NAME]${GIT_DESCRIBE}"
      gcc --version
      g++ --version
    displayName: git describe

  - bash: |
      sudo apt-get update
      sudo apt-get install -y libgtk-3-dev
      mkdir -p build/wxWidgets
      cd build/wxWidgets
      ../../lib-src/wxWidgets/configure --with-gtk=3
      make -j 4
      sudo make -j 4 install
      sudo ldconfig
    displayName: Build wxWidgets

  - bash: |
      sudo apt-get install -y libasound2-dev libavformat-dev libjack-jackd2-dev
      mkdir -p build/audacity
      cd build/audacity
      ../../configure WX_CONFIG=../wxWidgets/wx-config --with-lib-preference="local system" --with-ffmpeg="system" --disable-dynamic-loading
      make -j 4
    displayName: Build Audacity

