trigger:
- build

jobs:
- template: 'azure/msvc-job.yml'
  parameters:
    name: 'Win32'
    platform: 'Win32'

- template: 'azure/linux-job.yml'
  parameters:
    name: 'Linux'

#- template: 'azure/macos-job.yml'

#- template: 'azure/macos-job.yml'
#  parameters:
#    name: 'macOS_x64'
#    configuration: 'Release64'

